# Conda configuration file to reproduce computing environment
#
# Create the conda environment:
# conda env create -n tb-suscept --file environment.yaml
#
# Activate the conda environment:
# source activate tb-suscept
#
# Deactivate the conda environmnet:
# source deactivate tb-suscept
#
# https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html
# https://conda.io/docs/using/envs.html#create-environment-file-by-hand
# https://bioconda.github.io
# https://anaconda.org/jdblischak/repo

name: tb-suscept
channels:
  - jdblischak
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - bioawk
  - bioconductor-affy
  - bioconductor-biobase
  - bioconductor-biomart
  - bioconductor-edger
  - bioconductor-geoquery
  - bioconductor-genomicranges
  - bioconductor-limma
  - bioconductor-snplocs.hsapiens.dbsnp144.grch38
  - fastqc
  - make
  - multiqc
  - pypdf2
  - python
  - python-docx
  - r=3.3.2
  - r-ashr
  - r-caret
  - r-cowplot
  - r-data.table
  - r-dplyr
  - r-dt
  - r-flux
  - r-gdata
  - r-ggbeeswarm
  - r-ggdendro
  - r-ggplot2
  - r-glmnet
  - r-gplots
  - r-gridextra
  - r-hmisc
  - r-kernlab
  - r-knitr
  - r-openxlsx
  - r-plyr
  - r-randomforest
  - r-rcolorbrewer
  - r-rmarkdown
  - r-stringr
  - r-tidyr
  - r-venndiagram
  - samtools
  - snakemake
  - subread
  - texlive-core
