---
title: "Initial analysis with limma"
date: 2016-05-27
output:
  html_document:
    toc: true
    toc_float: true
---

**Last updated:** `r Sys.Date()`

**Code version:** `r system("git log -1 --format='%H'", intern = TRUE)`

```{r chunk-options}
library("knitr")
opts_chunk$set(cache = FALSE)
```

Initial limma analysis.

## Setup

```{r packages, message=FALSE}
library("limma")
library("edgeR")
library("data.table")
library("dplyr")
library("tidyr")
library("ggplot2")
library("cowplot")
theme_set(theme_bw(base_size = 12))
```

Input data.

```{r input-counts}
counts <- read.delim("../data/counts.txt", check.names = FALSE, row.names = 1)
anno <- read.delim("../data/experiment-info.txt", stringsAsFactors = FALSE)
rownames(anno) <- anno$id
anno <- anno %>% select(-id, -tube_ind)
stopifnot(colnames(counts) == rownames(anno))
```

## Model with limma

```{r design-matrix}
anno$status <- factor(anno$status, levels = c("contact", "tb"))
anno$treatment <- factor(anno$treatment, levels = c("none", "infected"))
design <- model.matrix(~treatment + status + status:treatment,
                       data = anno)
colnames(design)[1] <- "Intercept"
colnames(design) <- gsub("treatment", "", colnames(design))
colnames(design) <- gsub("status", "", colnames(design))
colnames(design) <- gsub(":", ".", colnames(design))
colnames(design)
```

```{r fit-model, fig.width=8}
y <- DGEList(counts)
y <- calcNormFactors(y)
v <- voom(y, design)
# Model individual as a random effect
corfit <- duplicateCorrelation(v, design, block = anno$individual)
corfit$consensus
v <- voom(y, design, block = anno$individual, correlation = corfit$consensus)
fit <- lmFit(v, design, block = anno$individual, correlation = corfit$consensus)
fit <- eBayes(fit)
op <- par(mfrow = c(1, 3))
top_treatment <- topTable(fit, coef = "infected")
top_treatment
results_treatment <- topTable(fit, coef = "infected", number = nrow(counts), sort = "none")
plotMA(fit, coef = "infected")
hist(results_treatment$P.Value)
hist(results_treatment$adj.P.Val)
top_status <- topTable(fit, coef = "tb")
top_status
results_status <- topTable(fit, coef = "tb", number = nrow(counts), sort = "none")
plotMA(fit, coef = "tb")
hist(results_status$P.Value)
hist(results_status$adj.P.Val)
top_interaction <- topTable(fit, coef = "infected.tb")
top_interaction
results_interaction <- topTable(fit, coef = "infected.tb", number = nrow(counts), sort = "none")
plotMA(fit, coef = "infected.tb")
hist(results_interaction$P.Value)
hist(results_interaction$adj.P.Val)
par(op)
```

## Explore top hits

Boxplot function.

```{r boxplot-function}
plot_gene <- function(v, g) {
  # v - An EList object containing log2 counts per million
  # g - character vector of a single gene
  stopifnot(class(v) == "EList",
            is.character(g), length(g) == 1)
  library("tidyr")
  single_gene <- v$E[g, ]
  single_gene_long <- gather_(as.data.frame(single_gene),
                              gather_cols = colnames(single_gene))
  # For some reason, the argument value_col wouldn't work
  colnames(single_gene_long) <- "log2cpm"
  single_gene_long$sample <- rownames(single_gene_long)
  single_gene_long <- separate_(single_gene_long, col = "sample", sep = "-",
                                into = c("individual", "status", "treatment"))
  single_gene_long$status <- factor(single_gene_long$status, levels = c("contact", "tb"))
  single_gene_long$treatment <- factor(single_gene_long$treatment, levels = c("none", "infected"))
  ggplot(single_gene_long, aes(x = treatment, y = log2cpm, fill = status)) +
    geom_boxplot() +
    labs(title = g, x = "Treatment", y = expression("Expression level (" * log[2] * " cpm)"))
}
```

Infected.

```{r}
for (g in rownames(top_treatment)[1:3]) {
  print(plot_gene(v, g))
}
```

Susceptibility status.

```{r}
for (g in rownames(top_status)[1:3]) {
  print(plot_gene(v, g))
}
```

Interaction.

```{r}
for (g in rownames(top_interaction)[1:3]) {
  print(plot_gene(v, g))
}
```

## Session information

```{r info}
sessionInfo()
```
